<a href="https://colab.research.google.com/github/QossainAsim/Maths-For-Machine-Learning/blob/main/Vectors_Lecture_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
v = np.array([1,2,-1])
w = np.array([2,3,4])

In [ ]:
print(v+w)

[3 5 3]


In [ ]:
print(v-w)

[-1 -1 -5]


Scalar Multiplication

In [ ]:
print(3*v)

[ 3  6 -3]


Now we are going to use a few function linalg for LINEAR ALGEBRA and norm for LENGTH

In [ ]:
print(np.linalg.norm(v))

2.449489742783178


For Dot Product

In [ ]:
s = np.dot(v,w)
print(s)

4


Here is the end for the implemention rest of the practice we do by ourselves.