<a href="https://colab.research.google.com/github/QossainAsim/Maths-For-Machine-Learning/blob/main/Vectors_Lecture_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
v = np.array([1,2,-1])
w = np.array([2,3,4])

In [ ]:
print(v+w)

[3 5 3]


In [ ]:
print(v-w)

[-1 -1 -5]


Scalar Multiplication

In [ ]:
print(3*v)

[ 3  6 -3]


Now we are going to use a few function linalg for LINEAR ALGEBRA and norm for LENGTH

In [ ]:
print(np.linalg.norm(v))

2.449489742783178


For Dot Product

In [ ]:
s = np.dot(v,w)
print(s)

4


MATRIX OPERATIONS


In [3]:
M = np.array([[2,3,4], [5,7,8], [9,5,6]])
print(M)

[[2 3 4]
 [5 7 8]
 [9 5 6]]


In [6]:
N = np.array([[3,2,1],[7,8,9],[6,5,7]])
print(N)

[[3 2 1]
 [7 8 9]
 [6 5 7]]


In [12]:
Addition_1 = np.add(M,N)
print(Addition_1)

[[ 5  5  5]
 [12 15 17]
 [15 10 13]]


Now here we can test on thing A + B = B + A but A - B != B - A


In [13]:
Addition_2 = np.add(N,M)
print(Addition_2)

[[ 5  5  5]
 [12 15 17]
 [15 10 13]]


In [16]:
if np.array_equal(Addition_1, Addition_2):
  print("Equal")
else:
  print("Not Equal")

Equal


Subtraction

In [17]:
Sub_1 = np.subtract(N,M)
print(Sub_1)

[[ 1 -1 -3]
 [ 2  1  1]
 [-3  0  1]]


In [18]:
Sub_2 = np.subtract(M,N)
print(Sub_2)

[[-1  1  3]
 [-2 -1 -1]
 [ 3  0 -1]]


In [19]:
if np.array_equal(Sub_1, Sub_2):
  print("Equal")
else:
  print("Not Equal")

Not Equal


Multiplication

In [20]:
M = np.array([[2,3,4], [5,7,8], [9,5,6]])
print(M)

[[2 3 4]
 [5 7 8]
 [9 5 6]]


In [21]:
N = np.array([[3,2],[7,8],[6,5]])
print(N)

[[3 2]
 [7 8]
 [6 5]]


multiply (or *) → Element‑wise product. Multiplies arrays position‑by‑position; shapes must be identical or broadcastable. No matrix multiplication logic.

matmul (or @) → Matrix product. For 2‑D: classical row‑×‑column multiplication. For N‑D: treats the last two axes as matrices and batches over the leading dimensions (broadcast if needed).

dot → Sum‑over‑axes product. For 2‑D: same as matmul. For N‑D: sums over the last axis of the first array and the second‑to‑last of the second, keeping all other dimensions – no batch behaviour; result shape differs from matmul when both arrays are 3‑D or higher.

In [22]:
Mul = np.dot(M,N)
print(Mul)

[[ 51  48]
 [112 106]
 [ 98  88]]


In [23]:
Mul = np.matmul(M,N)
print(Mul)

[[ 51  48]
 [112 106]
 [ 98  88]]


In machine learning (especially deep learning), the choice is simple:

matmul (@) Use this for nearly everything.

Handles batched linear transformations automatically: (batch, features) @ (features, units) → (batch, units).

Used in fully‑connected layers, attention (Q @ K^T), and any operation where you multiply matrices with a leading batch dimension.

Works cleanly in frameworks like NumPy, PyTorch, TensorFlow, and JAX with the @ operator.

dot — Rarely used in modern ML code.

Mainly for simple 1‑D vector inner products: np.dot(u, v) → scalar (same as u @ v).

Has unpredictable behaviour for 3‑D+ arrays (it does not batch; it sums over non‑matching axes), which leads to subtle bugs.

Therefore, even for vector dot products, many developers prefer @ for consistency.

Rule of thumb: If you see dot in ML code, it’s either legacy NumPy style or a 1‑D dot product. For everything else — including any multi‑dimensional operation reach for matmul/@.

In [25]:
# Two batches of 2x3 matrices
a = np.ones((2, 2, 3))    # shape (2,2,3)
b = np.ones((2, 3, 2))    # shape (2,3,2)

# matmul: batch multiplication, (2,2,3) @ (2,3,2) -> (2,2,2)
c_matmul = np.matmul(a, b)    # or a @ b
print("matmul shape:", c_matmul.shape)   # (2, 2, 2)

# dot: sums over last axis of a (3) and second-to-last of b (3),
#      keeps other axes -> (2,2) from a and (2,2) from b => (2,2,2,2)
c_dot = np.dot(a, b)
print("dot shape:   ", c_dot.shape)      # (2, 2, 2, 2)

matmul shape: (2, 2, 2)
dot shape:    (2, 2, 2, 2)


In [26]:
D = np.array([[2,3,4], [5,7,8], [9,5,6]])
print(D)

[[2 3 4]
 [5 7 8]
 [9 5 6]]


In [28]:
det = np.linalg.det(D)
print(det)

-22.000000000000014


In [33]:
S = np.array([[1,0,2], [0,1,3], [1,1,5]])
print(S)

[[1 0 2]
 [0 1 3]
 [1 1 5]]


In [34]:
s_det = np.linalg.det(S)
print(s_det)

0.0


Inverse to check its singular or not

In [35]:
Sin = np.linalg.inv(S)

LinAlgError: Singular matrix

In [36]:
cond = np.linalg.cond(S)
print(cond)   # ~1e16 or higher → matrix is effectively singular

3.4669335038692412e+16


In [37]:
E = np.array([[2,3],[4,5]])
print(np.linalg.inv(E))

[[-2.5  1.5]
 [ 2.  -1. ]]
